import React from 'react';
import { CloseIcon } from './Icons';

const FullscreenModal = ({ generatedImage, onClose }) => (
  <div
    className="fixed inset-0 bg-opacity-90 z-50 flex items-center justify-center p-4 fullscreen-modal overflow-auto"
    tabIndex={-1}
    aria-modal="true"
    role="dialog"
  >
    <div className="relative max-w-full max-h-full shadow-2xl rounded-xl bg-[var(--md3-surface)] p-2 overflow-hidden">
      <img
        src={generatedImage}
        alt="Generated by AI"
        className="max-w-[100vw] max-h-[100vh] object-contain rounded-lg"
        loading="lazy"
        decoding="async"
      />
      <button
        onClick={onClose}
        className="absolute top-4 right-4 md3-btn-icon bg-black bg-opacity-50 hover:bg-opacity-70 focus:outline-none focus:ring-2 focus:ring-[var(--md3-primary)]"
        title="Close"
        aria-label="Close fullscreen image"
        autoFocus
      >
        <CloseIcon />
      </button>
    </div>
  </div>
);

export default FullscreenModal; 