import React from 'react';
import { CopyIcon, DownloadIcon, ViewIcon, CloseIcon } from './Icons';

const ImageDisplay = ({
  generatedImage,
  onShowImageDetails,
  onCopyPrompt,
  onToggleFullscreen,
  isFullscreen,
  prompt
}) => (
  <>
    <div className="md3-card w-full h-full max-w-4xl max-h-full flex flex-col">
      <div className="flex-1 flex items-center justify-center overflow-hidden rounded-lg">
        <img
          src={generatedImage}
          alt="Generated by AI"
          className="w-full h-full object-contain rounded-lg"
          loading="lazy"
          decoding="async"
        />
      </div>
    </div>
    <div className="flex items-center mt-4 p-4 max-w-4xl mx-auto gap-3">
      <button
        onClick={onShowImageDetails}
        className="md3-btn-icon bg-black group relative bg-opacity-50 hover:bg-opacity-70 w-8 h-8 sm:w-10 sm:h-10 flex items-center justify-center"
      >
        <span className="text-white font-bold text-base sm:text-xl">i</span>
        <span className="absolute bottom-full bottom-1/2 -translate-y-1/2 bg-black text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
          image details
        </span>
      </button>
      <button
        onClick={onCopyPrompt}
        className="md3-btn-icon group relative w-8 h-8 sm:w-10 sm:h-10 flex items-center justify-center"
      >
        <span className="text-base sm:text-xl"><CopyIcon /></span>
        <span className="absolute bottom-full bottom-1/2 -translate-y-1/2 bg-black text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
          Copy Prompt
        </span>
      </button>
      {generatedImage && (
        <a
          href={`/api/proxy-image?url=${encodeURIComponent(generatedImage)}`}
          download={`generated-image-${Date.now()}.webp`}
          className="md3-btn-icon group relative w-8 h-8 sm:w-10 sm:h-10 flex items-center justify-center"
        >
          <span className="text-base sm:text-xl"><DownloadIcon /></span>
          <span className="absolute bottom-full bottom-1/2 -translate-y-1/2 bg-black text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
            Download
          </span>
        </a>
      )}
      <button
        onClick={onToggleFullscreen}
        className="md3-btn-icon group relative w-8 h-8 sm:w-10 sm:h-10 flex items-center justify-center"
      >
        <span className="text-base sm:text-xl">{isFullscreen ? <CloseIcon /> : <ViewIcon />}</span>
        <span className="absolute bottom-full bottom-1/2 -translate-y-1/2 bg-black text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
          {isFullscreen ? "Exit Fullscreen" : "Fullscreen"}
        </span>
      </button>
    </div>
  </>
);

export default ImageDisplay; 